apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: q5n2xk4mj-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b0a82524dc.hncd.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:01521c0705a26bf58466b3aeeede7c5c7f4bbaaf@sha256:ce808b9c1725346bc14cea1c11770d867d26a24041fd89127b8e2df3bb7e4a0b
          name: container-image
